### PR TITLE
integratd signup page

### PR DESCRIPTION
**Pull request by Sharmaryan**
Screenshot (44)

added signup page

### CODE REVIEW

**Review by samyakshah3008 — APPROVED** [review]
Looks good to go
just a small suggestion in UI:  
Give padding in input and margins as well for better experience 
Rest part is all good, nice work!

**Comment by Sharmaryan** [comment]
> Looks good to go just a small suggestion in UI: Give padding in input and margins as well for better experience Rest part is all good, nice work!

sure will change it

**Review by zabihshaik — APPROVED** [review]
Everything looks good.

**Comment by preethasri** [comment]
Looks good aryan 👍

**Pull request merged**
